package index

import (
	"encoding/binary"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// The parity fixture, generated by scripts/dump_parity_fixtures.py from
// faiss.IndexFlatIP. Regenerate deliberately.
const searchFixture = "../../../testdata/search_cases.json"

type searchCase struct {
	Name           string      `json:"name"`
	K              int         `json:"k"`
	Dim            int         `json:"dim"`
	Vectors        [][]float32 `json:"vectors"`
	Queries        [][]float32 `json:"queries"`
	ExpectedItems  [][]int32   `json:"expected_items"`
	ExpectedScores [][]float32 `json:"expected_scores"`
}

// build writes the fixture's table to disk in the artifact format and loads it,
// so the test exercises the real loader rather than a hand-built struct. A
// decode bug would otherwise pass every parity case.
func (c searchCase) build(t *testing.T) *Flat {
	t.Helper()
	stem := filepath.Join(t.TempDir(), "items")

	body := make([]byte, 0, len(c.Vectors)*c.Dim*4)
	for _, row := range c.Vectors {
		for _, value := range row {
			word := make([]byte, 4)
			binary.LittleEndian.PutUint32(word, math.Float32bits(value))
			body = append(body, word...)
		}
	}
	if err := os.WriteFile(stem+".bin", body, 0o600); err != nil {
		t.Fatalf("writing vectors: %v", err)
	}

	raw, err := json.Marshal(Meta{
		Rows: len(c.Vectors), Dim: c.Dim, BaseIndex: 1, Version: "v=parity",
	})
	if err != nil {
		t.Fatalf("marshalling meta: %v", err)
	}
	if err := os.WriteFile(stem+".json", raw, 0o600); err != nil {
		t.Fatalf("writing meta: %v", err)
	}

	flat, err := Load(stem)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	return flat
}

func loadSearchCases(t *testing.T) []searchCase {
	t.Helper()
	raw, err := os.ReadFile(filepath.Clean(searchFixture))
	if err != nil {
		t.Fatalf("reading fixture: %v (run `uv run python -m scripts.dump_parity_fixtures`)", err)
	}
	var cases []searchCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("fixture is empty; a parity test over no cases passes and proves nothing")
	}
	return cases
}

// TestExactSearchMatchesFAISS is the sixth parity surface, and its scope is
// narrower than "rung 2 serves what rung 1 serves" -- deliberately.
//
// Rung 1 is HNSW, which is approximate: Part J measured it agreeing with exact
// search on 0.9866 of candidates. Rung 2 therefore cannot reproduce rung 1
// slate for slate and should not try. What this pins is that the Go scan
// computes the same EXACT answer FAISS computes, so the rung-1-to-rung-2
// difference is precisely the approximate-vs-exact gap already measured,
// rather than an unknown quantity stacked on top of it.
//
// Scored items and their grouping are compared exactly; ORDER WITHIN A TIE is
// not, because FAISS has no stable order there to compare against. See the
// note on index.Flat.Search for the measurement behind that.
func TestExactSearchMatchesFAISS(t *testing.T) {
	for _, testCase := range loadSearchCases(t) {
		t.Run(testCase.Name, func(t *testing.T) {
			flat := testCase.build(t)

			for query := range testCase.Queries {
				items, scores, err := flat.Search(testCase.Queries[query], testCase.K)
				if err != nil {
					t.Fatalf("query %d: %v", query, err)
				}

				// FAISS pads a short result with -1, which to_item_ids maps to
				// 0; the Go scan returns a short slice instead. Compared over
				// the real answers only, and the padding is checked separately
				// below so neither behaviour is asserted by accident.
				want := testCase.ExpectedItems[query]
				real := 0
				for _, item := range want {
					if item > 0 {
						real++
					}
				}

				if len(items) != real {
					t.Fatalf("query %d: %d items, FAISS found %d", query, len(items), real)
				}

				wantScores := testCase.ExpectedScores[query]
				// Compared in EQUAL-SCORE GROUPS rather than slot by slot.
				//
				// Order within a tie is deliberately unconstrained, because
				// FAISS has no stable order to compare against: measured on
				// identical rows it keeps the earlier row at k=1 and the later
				// at k=5 and k=100, since the k=1 path and the heap path are
				// different code. Asserting a slot-by-slot match would be
				// asserting one of FAISS's two behaviours and failing on the
				// other. What IS checkable -- same items, same scores, same
				// grouping -- is checked.
				start := 0
				for start < real {
					end := start + 1
					for end < real && closeEnough(wantScores[end], wantScores[start]) {
						end++
					}

					// A tie group running to the end of a FULL result may have
					// been truncated by k, and the two implementations can
					// then legitimately keep different members of it. Only the
					// size is comparable there.
					truncated := end == real && real == testCase.K && end-start > 1
					if !truncated && !sameItems(items[start:end], want[start:end]) {
						t.Errorf("query %d slots %d-%d: items %v, FAISS returned %v",
							query, start, end-1, items[start:end], want[start:end])
					}

					for slot := start; slot < end; slot++ {
						if !closeEnough(scores[slot], wantScores[slot]) {
							t.Errorf("query %d slot %d: score %v, FAISS returned %v",
								query, slot, scores[slot], wantScores[slot])
						}
					}
					start = end
				}
			}
		})
	}
}

func closeEnough(left, right float32) bool {
	return math.Abs(float64(left-right)) <= 1e-6
}

// sameItems compares two slots of a result as multisets.
func sameItems(got, want []int32) bool {
	if len(got) != len(want) {
		return false
	}
	counts := make(map[int32]int, len(want))
	for _, item := range want {
		counts[item]++
	}
	for _, item := range got {
		counts[item]--
		if counts[item] < 0 {
			return false
		}
	}
	return true
}

// TestTheFixtureContainsTheCasesThatCouldDiverge guards against a parity test
// that passes because it never asks anything hard.
//
// Three properties have to be present or the comparison above is vacuous: an
// exact tie (where the tie-break rule alone decides the slate), a negative
// best score (an implementation seeding its running best at zero passes every
// non-negative case), and a k larger than the table.
func TestTheFixtureContainsTheCasesThatCouldDiverge(t *testing.T) {
	cases := loadSearchCases(t)

	sawTie, sawNegative, sawShortTable := false, false, false
	for _, testCase := range cases {
		if testCase.K > len(testCase.Vectors) {
			sawShortTable = true
		}
		for _, row := range testCase.ExpectedScores {
			if len(row) > 0 && row[0] < 0 {
				sawNegative = true
			}
			// A tie at the top: the first two scores equal.
			if len(row) > 1 && math.Abs(float64(row[0]-row[1])) < 1e-9 {
				sawTie = true
			}
		}
	}

	if !sawTie {
		t.Error("no exact tie in the fixture; the tie-break rule is untested")
	}
	if !sawNegative {
		t.Error("no negative best score; a zero-seeded running best would pass")
	}
	if !sawShortTable {
		t.Error("no case with k past the table size")
	}
}
