package sources

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The parity fixture, generated by scripts/dump_parity_fixtures.py from
// models.reranking.seen.BloomFilter. Regenerate deliberately.
const seenFixture = "../../../testdata/seen_cases.json"

type seenCase struct {
	Name              string     `json:"name"`
	Capacity          int        `json:"capacity"`
	FalsePositiveRate float64    `json:"false_positive_rate"`
	Bits              uint64     `json:"bits"`
	Hashes            int        `json:"hashes"`
	Items             []int32    `json:"items"`
	ExpectedPositions [][]uint64 `json:"expected_positions"`
}

func loadSeenCases(t *testing.T) []seenCase {
	t.Helper()
	raw, err := os.ReadFile(filepath.Clean(seenFixture))
	if err != nil {
		t.Fatalf("reading fixture: %v (run `uv run python -m scripts.dump_parity_fixtures`)", err)
	}
	var cases []seenCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("fixture is empty; a parity test over no cases passes and proves nothing")
	}
	return cases
}

// TestSizingMatchesPython closes the loop the positions test opens.
//
// Every position is taken modulo `bits`, so agreeing on the hash and
// disagreeing on the size means agreeing on nothing. The two numbers are
// derived from (capacity, rate) on both sides rather than configured, so this
// is where that derivation is checked -- including Python's banker's rounding,
// which Go's math.Round does not reproduce.
func TestSizingMatchesPython(t *testing.T) {
	for _, testCase := range loadSeenCases(t) {
		t.Run(testCase.Name, func(t *testing.T) {
			bits, hashes := Sizing(testCase.Capacity, testCase.FalsePositiveRate)

			if bits != testCase.Bits {
				t.Errorf("bits = %d, Python produced %d", bits, testCase.Bits)
			}
			if hashes != testCase.Hashes {
				t.Errorf("hashes = %d, Python produced %d", hashes, testCase.Hashes)
			}
		})
	}
}

// TestSeenPositionsMatchPython is the fourth parity surface.
//
// The offline harness wrote these bits to measure what the filter costs the
// funnel; this package reads them in the request path. Disagreement is not a
// crash -- it is a filter that hides fresh items AND re-shows seen ones, which
// is precisely the failure the one-sided guarantee is supposed to make
// impossible.
//
// The arithmetic is the interesting part. `(base + i*step) % bits` on
// arbitrary-precision Python integers is exact; the same expression in uint64
// wraps at 2**64 first, and the two differ unless bits is a power of two. The
// fixture's later hash positions overflow, so a wrapping port fails here
// rather than in production.
func TestSeenPositionsMatchPython(t *testing.T) {
	for _, testCase := range loadSeenCases(t) {
		t.Run(testCase.Name, func(t *testing.T) {
			filter := NewSeenList(nil, testCase.Bits, testCase.Hashes)

			for index, item := range testCase.Items {
				got := filter.Positions(item)
				want := testCase.ExpectedPositions[index]

				if len(got) != len(want) {
					t.Fatalf("item %d: %d positions, Python produced %d",
						item, len(got), len(want))
				}
				for slot := range want {
					if got[slot] != want[slot] {
						t.Errorf("item %d, hash %d: got %d, Python produced %d",
							item, slot, got[slot], want[slot])
					}
				}
			}
		})
	}
}

// TestPositionsStayInRange is the cheap invariant behind the parity one. A
// position past the bitmap is not a wrong answer, it is an out-of-range write
// that Redis would happily accept and grow the string for.
func TestPositionsStayInRange(t *testing.T) {
	filter := NewSeenList(nil, 1918, 7)

	for item := int32(1); item < 500; item++ {
		for _, position := range filter.Positions(item) {
			if position >= filter.Bits {
				t.Fatalf("item %d produced position %d for a %d-bit filter",
					item, position, filter.Bits)
			}
		}
	}
}

// TestBitOrderIsBigEndianWithinTheByte pins the half of the format that is not
// arithmetic.
//
// Redis numbers bit 0 as the HIGH bit of byte 0, matching numpy's
// `unpackbits(bitorder="big")`. Reversed, the filter answers plausibly and
// wrongly with no error anywhere -- and every unit test written against the
// same reversal would agree with it.
func TestBitOrderIsBigEndianWithinTheByte(t *testing.T) {
	// 0b1000_0001: bits 0 and 7 set, nothing between.
	raw := []byte{0x81}

	for position, want := range map[uint64]bool{0: true, 1: false, 6: false, 7: true} {
		if got := bitSet(raw, position); got != want {
			t.Errorf("bit %d = %v, want %v", position, got, want)
		}
	}
}

// TestAShortBitmapReadsAsUnset: Redis grows the string only as far as the
// highest bit ever SET, so a sparse filter comes back short. The Python side
// pads for the same reason.
func TestAShortBitmapReadsAsUnset(t *testing.T) {
	if bitSet([]byte{0xFF}, 64) {
		t.Error("a position past the end of the bitmap must read as unset")
	}
	if bitSet(nil, 0) {
		t.Error("an absent bitmap must read as unset")
	}
}
