# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\trecsys.v1\"\x86\x02\n\x10InteractionEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07item_id\x18\x03 \x01(\t\x12\x12\n\nevent_type\x18\x04 \x01(\t\x12\x13\n\x0b\x65vent_ts_ms\x18\x05 \x01(\x03\x12\x14\n\x0cingest_ts_ms\x18\x06 \x01(\x03\x12\x12\n\nsession_id\x18\x07 \x01(\t\x12\x10\n\x08position\x18\x08 \x01(\x05\x12\x12\n\nrequest_id\x18\t \x01(\t\x12\x10\n\x08\x64well_ms\x18\n \x01(\x03\x12\x12\n\npropensity\x18\x0b \x01(\x02\x12\x0e\n\x06\x64\x65vice\x18\x0c \x01(\t\x12\x0f\n\x07surface\x18\r \x01(\tBMZKgithub.com/MattyChoi/Recommendation-System-Design/serving/go/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/MattyChoi/Recommendation-System-Design/serving/go/internal/pb;pb'
  _globals['_INTERACTIONEVENT']._serialized_start=28
  _globals['_INTERACTIONEVENT']._serialized_end=290
# @@protoc_insertion_point(module_scope)
