# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.pb import features_pb2 as features__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in features_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeaturesStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/recsys.v1.Features/GetUser',
                request_serializer=features__pb2.GetUserRequest.SerializeToString,
                response_deserializer=features__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.GetItems = channel.unary_unary(
                '/recsys.v1.Features/GetItems',
                request_serializer=features__pb2.GetItemsRequest.SerializeToString,
                response_deserializer=features__pb2.GetItemsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/recsys.v1.Features/Health',
                request_serializer=features__pb2.FeaturesHealthRequest.SerializeToString,
                response_deserializer=features__pb2.FeaturesHealthResponse.FromString,
                _registered_method=True)


class FeaturesServicer:
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Everything about the user that the fan-out and the ranker both need,
        fetched ONCE. §14.2 fetches user features and history in parallel before
        retrieval; splitting them across two calls would let the retriever and the
        ranker see two different snapshots of the same user mid-request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItems(self, request, context):
        """Per-item features for the ranker's candidate set. Separate from GetUser
        because it happens LATER -- the candidates do not exist until retrieval
        and filtering have run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeaturesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=features__pb2.GetUserRequest.FromString,
                    response_serializer=features__pb2.GetUserResponse.SerializeToString,
            ),
            'GetItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItems,
                    request_deserializer=features__pb2.GetItemsRequest.FromString,
                    response_serializer=features__pb2.GetItemsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=features__pb2.FeaturesHealthRequest.FromString,
                    response_serializer=features__pb2.FeaturesHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recsys.v1.Features', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recsys.v1.Features', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Features:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recsys.v1.Features/GetUser',
            features__pb2.GetUserRequest.SerializeToString,
            features__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recsys.v1.Features/GetItems',
            features__pb2.GetItemsRequest.SerializeToString,
            features__pb2.GetItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recsys.v1.Features/Health',
            features__pb2.FeaturesHealthRequest.SerializeToString,
            features__pb2.FeaturesHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
