// The raw interaction event log.
//
// Regenerate stubs after any edit:  make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`       // impression|click|watch|cart|purchase
	EventTsMs     int64                  `protobuf:"varint,5,opt,name=event_ts_ms,json=eventTsMs,proto3" json:"event_ts_ms,omitempty"`    // when it HAPPENED
	IngestTsMs    int64                  `protobuf:"varint,6,opt,name=ingest_ts_ms,json=ingestTsMs,proto3" json:"ingest_ts_ms,omitempty"` // when we LEARNED about it
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Position      int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`                   // slot shown in -- for position bias
	RequestId     string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // joins impressions to clicks
	DwellMs       int64                  `protobuf:"varint,10,opt,name=dwell_ms,json=dwellMs,proto3" json:"dwell_ms,omitempty"`
	Propensity    float32                `protobuf:"fixed32,11,opt,name=propensity,proto3" json:"propensity,omitempty"` // P(shown | policy) -- log it, thank yourself later
	Device        string                 `protobuf:"bytes,12,opt,name=device,proto3" json:"device,omitempty"`
	Surface       string                 `protobuf:"bytes,13,opt,name=surface,proto3" json:"surface,omitempty"` // home_rail|search|detail_page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionEvent) Reset() {
	*x = InteractionEvent{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionEvent) ProtoMessage() {}

func (x *InteractionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionEvent.ProtoReflect.Descriptor instead.
func (*InteractionEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *InteractionEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *InteractionEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InteractionEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InteractionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *InteractionEvent) GetEventTsMs() int64 {
	if x != nil {
		return x.EventTsMs
	}
	return 0
}

func (x *InteractionEvent) GetIngestTsMs() int64 {
	if x != nil {
		return x.IngestTsMs
	}
	return 0
}

func (x *InteractionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InteractionEvent) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *InteractionEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InteractionEvent) GetDwellMs() int64 {
	if x != nil {
		return x.DwellMs
	}
	return 0
}

func (x *InteractionEvent) GetPropensity() float32 {
	if x != nil {
		return x.Propensity
	}
	return 0
}

func (x *InteractionEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *InteractionEvent) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\trecsys.v1\"\x87\x03\n" +
	"\x10InteractionEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x1e\n" +
	"\vevent_ts_ms\x18\x05 \x01(\x03R\teventTsMs\x12 \n" +
	"\fingest_ts_ms\x18\x06 \x01(\x03R\n" +
	"ingestTsMs\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\x12\x19\n" +
	"\bdwell_ms\x18\n" +
	" \x01(\x03R\adwellMs\x12\x1e\n" +
	"\n" +
	"propensity\x18\v \x01(\x02R\n" +
	"propensity\x12\x16\n" +
	"\x06device\x18\f \x01(\tR\x06device\x12\x18\n" +
	"\asurface\x18\r \x01(\tR\asurfaceBMZKgithub.com/MattyChoi/Recommender-System-Design/serving/go/internal/pb;pbb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_proto_goTypes = []any{
	(*InteractionEvent)(nil), // 0: recsys.v1.InteractionEvent
}
var file_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
