// The feature gateway's contract: entity ids in, feature vectors out.
//
// Regenerate stubs after any edit:  make proto
//
// Why this is a service and not a library call: Feast's online store is read
// through Feast's own SDK, and its Redis encoding is a Feast-internal protobuf
// layout. Reimplementing that in Go would couple the request path to a
// third-party wire format whose changes look like corrupt features rather than
// like a version mismatch. So Feast is used the way it is meant to be used,
// from Python, behind one hop.
//
// **This gateway owns the ORDER of every feature vector it returns.** That
// order is not cosmetic: the ranker's ONNX graph was exported against a fixed
// column order and cannot detect a permutation -- the shape is right, the dtype
// is right, and the model scores a different world in silence. The orchestrator
// carries the names alongside the values for exactly that reason and checks
// them before scoring.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: features.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The external user id: Feast's entity key, and the same string the
	// retrieval sidecar takes.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// How much history to return. The tower pools at most MAX_HISTORY, so more
	// than that is bytes on the wire nothing reads.
	MaxHistory    int32 `protobuf:"varint,2,opt,name=max_history,json=maxHistory,proto3" json:"max_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_features_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRequest) GetMaxHistory() int32 {
	if x != nil {
		return x.MaxHistory
	}
	return 0
}

type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Values in `names` order, ready to hand to the tower.
	Values []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	// The column names, travelling WITH the values. The one part of the contract
	// that cannot be checked by shape: a permuted vector is the right length and
	// the right type, and produces a plausible embedding for a user who does not
	// exist.
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	// Recent history as INTERNAL item indices, most recent first.
	//
	// Translated here rather than in the orchestrator. Feast stores
	// `last_50_items` as external id strings and the tower indexes an embedding
	// table by position, so someone must map them; doing it here keeps the
	// item_map in one process rather than two that can be a build apart.
	History []int32 `protobuf:"varint,3,rep,packed,name=history,proto3" json:"history,omitempty"`
	// Items in `last_50_items` that the item_map did not know. Reported rather
	// than dropped in silence: a rising count means the map and the feature
	// store are drifting apart, which otherwise shows up as users mysteriously
	// looking colder than they are.
	UnmappedHistory int32 `protobuf:"varint,4,opt,name=unmapped_history,json=unmappedHistory,proto3" json:"unmapped_history,omitempty"`
	// False when the store had no row for this user and defaults were served.
	// §14.2 degrades rather than failing on a feature miss, and a miss rate that
	// climbs is the signal that materialisation has stopped.
	Found         bool `protobuf:"varint,5,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_features_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetUserResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *GetUserResponse) GetHistory() []int32 {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetUserResponse) GetUnmappedHistory() int32 {
	if x != nil {
		return x.UnmappedHistory
	}
	return 0
}

func (x *GetUserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal item indices, in candidate order.
	Items         []int32 `protobuf:"varint,1,rep,packed,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_features_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemsRequest) GetItems() []int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One row per requested item, in REQUEST order, flattened row-major.
	//
	// Flat rather than repeated-message: the orchestrator reshapes it into the
	// ranker's matrix, and a message per candidate would allocate ~500 objects
	// per request to carry ~11 floats each.
	Values []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	// Column names for every row. Same reason as GetUserResponse.names.
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	// Per-item, aligned with the request: false where the store had no row and
	// defaults were used. A cold article is normal on a news corpus; ALL of them
	// being cold is a broken materialisation.
	Found []bool `protobuf:"varint,3,rep,packed,name=found,proto3" json:"found,omitempty"`
	// How many of these rows came from the gateway's in-process cache rather
	// than from Feast.
	//
	// On the wire because a cache that has quietly stopped being hit is a
	// latency regression with NO ERROR ATTACHED -- and this one is load-bearing:
	// assembling 400 uncached rows costs 9.7ms at p50 and 126ms at p99, holds
	// the GIL while it does, and starves GetUser into missing its 8ms budget.
	// The retrieval sidecar carries `embedding_cached` for the same reason.
	Cached        int32 `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_features_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemsResponse) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetItemsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *GetItemsResponse) GetFound() []bool {
	if x != nil {
		return x.Found
	}
	return nil
}

func (x *GetItemsResponse) GetCached() int32 {
	if x != nil {
		return x.Cached
	}
	return 0
}

type FeaturesHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturesHealthRequest) Reset() {
	*x = FeaturesHealthRequest{}
	mi := &file_features_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturesHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturesHealthRequest) ProtoMessage() {}

func (x *FeaturesHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturesHealthRequest.ProtoReflect.Descriptor instead.
func (*FeaturesHealthRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{4}
}

type FeaturesHealthResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ready  bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Detail string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	// How stale the online store is, by its own event timestamps. docs/design.md
	// budgets features as daily and hourly; an alert on freshness lag > 10
	// minutes is meaningless without a number to alert on.
	OldestFeatureAgeSeconds int64 `protobuf:"varint,3,opt,name=oldest_feature_age_seconds,json=oldestFeatureAgeSeconds,proto3" json:"oldest_feature_age_seconds,omitempty"`
	// The item_map snapshot used for history translation, so a gateway and an
	// index built from different maps can be told apart.
	ItemMapVersion string `protobuf:"bytes,4,opt,name=item_map_version,json=itemMapVersion,proto3" json:"item_map_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeaturesHealthResponse) Reset() {
	*x = FeaturesHealthResponse{}
	mi := &file_features_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturesHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturesHealthResponse) ProtoMessage() {}

func (x *FeaturesHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturesHealthResponse.ProtoReflect.Descriptor instead.
func (*FeaturesHealthResponse) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{5}
}

func (x *FeaturesHealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *FeaturesHealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *FeaturesHealthResponse) GetOldestFeatureAgeSeconds() int64 {
	if x != nil {
		return x.OldestFeatureAgeSeconds
	}
	return 0
}

func (x *FeaturesHealthResponse) GetItemMapVersion() string {
	if x != nil {
		return x.ItemMapVersion
	}
	return ""
}

var File_features_proto protoreflect.FileDescriptor

const file_features_proto_rawDesc = "" +
	"\n" +
	"\x0efeatures.proto\x12\trecsys.v1\"J\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmax_history\x18\x02 \x01(\x05R\n" +
	"maxHistory\"\x9a\x01\n" +
	"\x0fGetUserResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12\x18\n" +
	"\ahistory\x18\x03 \x03(\x05R\ahistory\x12)\n" +
	"\x10unmapped_history\x18\x04 \x01(\x05R\x0funmappedHistory\x12\x14\n" +
	"\x05found\x18\x05 \x01(\bR\x05found\"'\n" +
	"\x0fGetItemsRequest\x12\x14\n" +
	"\x05items\x18\x01 \x03(\x05R\x05items\"n\n" +
	"\x10GetItemsResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12\x14\n" +
	"\x05found\x18\x03 \x03(\bR\x05found\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\x05R\x06cached\"\x17\n" +
	"\x15FeaturesHealthRequest\"\xad\x01\n" +
	"\x16FeaturesHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12;\n" +
	"\x1aoldest_feature_age_seconds\x18\x03 \x01(\x03R\x17oldestFeatureAgeSeconds\x12(\n" +
	"\x10item_map_version\x18\x04 \x01(\tR\x0eitemMapVersion2\xe0\x01\n" +
	"\bFeatures\x12@\n" +
	"\aGetUser\x12\x19.recsys.v1.GetUserRequest\x1a\x1a.recsys.v1.GetUserResponse\x12C\n" +
	"\bGetItems\x12\x1a.recsys.v1.GetItemsRequest\x1a\x1b.recsys.v1.GetItemsResponse\x12M\n" +
	"\x06Health\x12 .recsys.v1.FeaturesHealthRequest\x1a!.recsys.v1.FeaturesHealthResponseBJZHgithub.com/MattyChoi/Recommender-System-Design/serving/go/internal/pb;pbb\x06proto3"

var (
	file_features_proto_rawDescOnce sync.Once
	file_features_proto_rawDescData []byte
)

func file_features_proto_rawDescGZIP() []byte {
	file_features_proto_rawDescOnce.Do(func() {
		file_features_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_features_proto_rawDesc), len(file_features_proto_rawDesc)))
	})
	return file_features_proto_rawDescData
}

var file_features_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_features_proto_goTypes = []any{
	(*GetUserRequest)(nil),         // 0: recsys.v1.GetUserRequest
	(*GetUserResponse)(nil),        // 1: recsys.v1.GetUserResponse
	(*GetItemsRequest)(nil),        // 2: recsys.v1.GetItemsRequest
	(*GetItemsResponse)(nil),       // 3: recsys.v1.GetItemsResponse
	(*FeaturesHealthRequest)(nil),  // 4: recsys.v1.FeaturesHealthRequest
	(*FeaturesHealthResponse)(nil), // 5: recsys.v1.FeaturesHealthResponse
}
var file_features_proto_depIdxs = []int32{
	0, // 0: recsys.v1.Features.GetUser:input_type -> recsys.v1.GetUserRequest
	2, // 1: recsys.v1.Features.GetItems:input_type -> recsys.v1.GetItemsRequest
	4, // 2: recsys.v1.Features.Health:input_type -> recsys.v1.FeaturesHealthRequest
	1, // 3: recsys.v1.Features.GetUser:output_type -> recsys.v1.GetUserResponse
	3, // 4: recsys.v1.Features.GetItems:output_type -> recsys.v1.GetItemsResponse
	5, // 5: recsys.v1.Features.Health:output_type -> recsys.v1.FeaturesHealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_features_proto_init() }
func file_features_proto_init() {
	if File_features_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_features_proto_rawDesc), len(file_features_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_features_proto_goTypes,
		DependencyIndexes: file_features_proto_depIdxs,
		MessageInfos:      file_features_proto_msgTypes,
	}.Build()
	File_features_proto = out.File
	file_features_proto_goTypes = nil
	file_features_proto_depIdxs = nil
}
