// The feature gateway's contract: entity ids in, feature vectors out.
//
// Regenerate stubs after any edit:  make proto
//
// Why this is a service and not a library call: Feast's online store is read
// through Feast's own SDK, and its Redis encoding is a Feast-internal protobuf
// layout. Reimplementing that in Go would couple the request path to a
// third-party wire format whose changes look like corrupt features rather than
// like a version mismatch. So Feast is used the way it is meant to be used,
// from Python, behind one hop.
//
// **This gateway owns the ORDER of every feature vector it returns.** That
// order is not cosmetic: the ranker's ONNX graph was exported against a fixed
// column order and cannot detect a permutation -- the shape is right, the dtype
// is right, and the model scores a different world in silence. The orchestrator
// carries the names alongside the values for exactly that reason and checks
// them before scoring.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: features.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Features_GetUser_FullMethodName  = "/recsys.v1.Features/GetUser"
	Features_GetItems_FullMethodName = "/recsys.v1.Features/GetItems"
	Features_Health_FullMethodName   = "/recsys.v1.Features/Health"
)

// FeaturesClient is the client API for Features service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeaturesClient interface {
	// Everything about the user that the fan-out and the ranker both need,
	// fetched ONCE. §14.2 fetches user features and history in parallel before
	// retrieval; splitting them across two calls would let the retriever and the
	// ranker see two different snapshots of the same user mid-request.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// Per-item features for the ranker's candidate set. Separate from GetUser
	// because it happens LATER -- the candidates do not exist until retrieval
	// and filtering have run.
	GetItems(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*GetItemsResponse, error)
	Health(ctx context.Context, in *FeaturesHealthRequest, opts ...grpc.CallOption) (*FeaturesHealthResponse, error)
}

type featuresClient struct {
	cc grpc.ClientConnInterface
}

func NewFeaturesClient(cc grpc.ClientConnInterface) FeaturesClient {
	return &featuresClient{cc}
}

func (c *featuresClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, Features_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresClient) GetItems(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*GetItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemsResponse)
	err := c.cc.Invoke(ctx, Features_GetItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featuresClient) Health(ctx context.Context, in *FeaturesHealthRequest, opts ...grpc.CallOption) (*FeaturesHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeaturesHealthResponse)
	err := c.cc.Invoke(ctx, Features_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeaturesServer is the server API for Features service.
// All implementations must embed UnimplementedFeaturesServer
// for forward compatibility.
type FeaturesServer interface {
	// Everything about the user that the fan-out and the ranker both need,
	// fetched ONCE. §14.2 fetches user features and history in parallel before
	// retrieval; splitting them across two calls would let the retriever and the
	// ranker see two different snapshots of the same user mid-request.
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// Per-item features for the ranker's candidate set. Separate from GetUser
	// because it happens LATER -- the candidates do not exist until retrieval
	// and filtering have run.
	GetItems(context.Context, *GetItemsRequest) (*GetItemsResponse, error)
	Health(context.Context, *FeaturesHealthRequest) (*FeaturesHealthResponse, error)
	mustEmbedUnimplementedFeaturesServer()
}

// UnimplementedFeaturesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeaturesServer struct{}

func (UnimplementedFeaturesServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedFeaturesServer) GetItems(context.Context, *GetItemsRequest) (*GetItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItems not implemented")
}
func (UnimplementedFeaturesServer) Health(context.Context, *FeaturesHealthRequest) (*FeaturesHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFeaturesServer) mustEmbedUnimplementedFeaturesServer() {}
func (UnimplementedFeaturesServer) testEmbeddedByValue()                  {}

// UnsafeFeaturesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeaturesServer will
// result in compilation errors.
type UnsafeFeaturesServer interface {
	mustEmbedUnimplementedFeaturesServer()
}

func RegisterFeaturesServer(s grpc.ServiceRegistrar, srv FeaturesServer) {
	// If the following call panics, it indicates UnimplementedFeaturesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Features_ServiceDesc, srv)
}

func _Features_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Features_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Features_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Features_GetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServer).GetItems(ctx, req.(*GetItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Features_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeaturesHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeaturesServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Features_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeaturesServer).Health(ctx, req.(*FeaturesHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Features_ServiceDesc is the grpc.ServiceDesc for Features service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Features_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recsys.v1.Features",
	HandlerType: (*FeaturesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Features_GetUser_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _Features_GetItems_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Features_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "features.proto",
}
