// The serving contract: one request in, one ordered slate out.
//
// Regenerate stubs after any edit:  make proto
//
// Several fields here exist because of something this project measured rather
// than because a template had them. Each is marked at its definition; the
// short version:
//
//   - `propensity` cannot be reconstructed after the fact. By the time a
//     request is over, the candidate set and the random draw are both gone,
//     so an unlogged propensity is gone forever and every off-policy estimate
//     built later is biased. Part L's exploration arm is the only policy that
//     produces a usable one.
//   - `degraded_sources` and `used_fallback` exist because a recommender that
//     silently degrades looks healthy. Part I's blend drops slow sources
//     rather than waiting; without these two fields, "we returned 20 items"
//     and "we returned 20 items from one of five retrievers" are the same
//     response.
//   - `index_version` and `model_version` exist because Part J measured an
//     ANN parameter that was indistinguishable from exact on one checkpoint
//     and significantly worse on the next. A response that cannot say which
//     artifacts produced it cannot be debugged after a rebuild.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: recsys.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// home_rail | search | detail_page. Different surfaces have different slate
	// sizes and different diversity policies, so it is part of the request
	// rather than a deployment-wide constant.
	Surface    string `protobuf:"bytes,2,opt,name=surface,proto3" json:"surface,omitempty"`
	NumResults int32  `protobuf:"varint,3,opt,name=num_results,json=numResults,proto3" json:"num_results,omitempty"`
	// Client-side exclusions, ON TOP of the server's seen-list. The two are not
	// the same thing: the seen-list is what WE showed, this is what the caller
	// knows it has already rendered.
	ExcludeItemIds []string `protobuf:"bytes,4,rep,name=exclude_item_ids,json=excludeItemIds,proto3" json:"exclude_item_ids,omitempty"`
	// device, locale, and anything else the ranker takes as context.
	Context       map[string]string `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_recsys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recsys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_recsys_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendRequest) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *RecommendRequest) GetNumResults() int32 {
	if x != nil {
		return x.NumResults
	}
	return 0
}

func (x *RecommendRequest) GetExcludeItemIds() []string {
	if x != nil {
		return x.ExcludeItemIds
	}
	return nil
}

func (x *RecommendRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type ScoredItem struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ItemId string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// The score this item was ORDERED by -- after re-ranking, not the ranker's
	// raw output. Those differ whenever a policy fires, and reporting the
	// ranker's score beside a re-ranked order is how a debugging session starts
	// from a false premise.
	Score float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	// Per-stage numbers behind the decision: per-source retrieval scores,
	// p_click, the MMR penalty, the freshness multiplier. How "why did this
	// item show up?" gets answered without a rerun.
	DebugScores map[string]float32 `protobuf:"bytes,3,rep,name=debug_scores,json=debugScores,proto3" json:"debug_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// Which retrievers proposed it. Part I measured that a source can contribute
	// FEATURES without contributing candidates, so this is the set that actually
	// proposed the item, not the set that scored it.
	Sources []string `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	// P(this item in this slot | policy, history). **Log it or lose it.**
	// 1.0 means the slot was deterministic and carries no information for an
	// off-policy estimator; anything below 1.0 came from an exploration slot.
	Propensity float32 `protobuf:"fixed32,5,opt,name=propensity,proto3" json:"propensity,omitempty"`
	// 0-based slot. Recorded because the position-bias correction needs the slot
	// the SERVER chose -- Part K's position tower is built and deliberately
	// unwired precisely because MIND's logged order is shuffled and carries no
	// display signal. This field is what makes that ablation possible later, on
	// a log this project generated itself.
	Position      int32 `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredItem) Reset() {
	*x = ScoredItem{}
	mi := &file_recsys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredItem) ProtoMessage() {}

func (x *ScoredItem) ProtoReflect() protoreflect.Message {
	mi := &file_recsys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredItem.ProtoReflect.Descriptor instead.
func (*ScoredItem) Descriptor() ([]byte, []int) {
	return file_recsys_proto_rawDescGZIP(), []int{1}
}

func (x *ScoredItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ScoredItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoredItem) GetDebugScores() map[string]float32 {
	if x != nil {
		return x.DebugScores
	}
	return nil
}

func (x *ScoredItem) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ScoredItem) GetPropensity() float32 {
	if x != nil {
		return x.Propensity
	}
	return 0
}

func (x *ScoredItem) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type RecommendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*ScoredItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Which artifacts produced this response. Not decoration: an index rebuilt
	// on a schedule against a retrained model can silently change quality, and a
	// response that cannot name its versions cannot be attributed afterwards.
	ModelVersion      string `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	IndexVersion      string `protobuf:"bytes,3,opt,name=index_version,json=indexVersion,proto3" json:"index_version,omitempty"`
	ExperimentVariant string `protobuf:"bytes,4,opt,name=experiment_variant,json=experimentVariant,proto3" json:"experiment_variant,omitempty"`
	// Server-measured, end to end. The client's own timing includes the network
	// and is the number that matters to the client; this one is the number that
	// matters to whoever is optimising the service.
	LatencyMs int32 `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Per-stage milliseconds -- retrieval, filter, rank, rerank. A single
	// end-to-end number says a request was slow; this says which stage was.
	StageLatencyMs map[string]int32 `protobuf:"bytes,8,rep,name=stage_latency_ms,json=stageLatencyMs,proto3" json:"stage_latency_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// True when the pipeline could not produce a real slate and served the
	// popularity fallback instead. **A fallback that is not reported is an
	// outage that looks like a success.**
	UsedFallback bool `protobuf:"varint,6,opt,name=used_fallback,json=usedFallback,proto3" json:"used_fallback,omitempty"`
	// Retrievers that timed out or errored and were dropped. Empty is the
	// healthy case; a persistently non-empty list is a degraded service still
	// returning 200s.
	DegradedSources []string `protobuf:"bytes,7,rep,name=degraded_sources,json=degradedSources,proto3" json:"degraded_sources,omitempty"`
	// Candidates surviving each stage: retrieved, after filtering, after
	// ranking. Part L measured a seen-filter that, once saturated, blocks every
	// candidate -- which returns an empty slate while every component reports
	// success. These counts are how that is caught in production rather than in
	// a postmortem.
	StageCounts   map[string]int32 `protobuf:"bytes,9,rep,name=stage_counts,json=stageCounts,proto3" json:"stage_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_recsys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recsys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_recsys_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendResponse) GetItems() []*ScoredItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecommendResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *RecommendResponse) GetIndexVersion() string {
	if x != nil {
		return x.IndexVersion
	}
	return ""
}

func (x *RecommendResponse) GetExperimentVariant() string {
	if x != nil {
		return x.ExperimentVariant
	}
	return ""
}

func (x *RecommendResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RecommendResponse) GetStageLatencyMs() map[string]int32 {
	if x != nil {
		return x.StageLatencyMs
	}
	return nil
}

func (x *RecommendResponse) GetUsedFallback() bool {
	if x != nil {
		return x.UsedFallback
	}
	return false
}

func (x *RecommendResponse) GetDegradedSources() []string {
	if x != nil {
		return x.DegradedSources
	}
	return nil
}

func (x *RecommendResponse) GetStageCounts() map[string]int32 {
	if x != nil {
		return x.StageCounts
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_recsys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recsys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_recsys_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ready bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Why not, when not ready. A boolean alone sends someone to the logs.
	Detail       string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	ModelVersion string `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	IndexVersion string `protobuf:"bytes,4,opt,name=index_version,json=indexVersion,proto3" json:"index_version,omitempty"`
	// "hnsw" or "flat". ADR 0002 ships HNSW and keeps exact search as the
	// load-failure fallback -- which means a server that quietly failed over is
	// serving correct results 6x slower, and every latency alert fires at once
	// with no explanation. The mode is reported so the cause is one call away.
	IndexKind string `protobuf:"bytes,5,opt,name=index_kind,json=indexKind,proto3" json:"index_kind,omitempty"`
	// The `efSearch` actually loaded. ADR 0002 picks 512 over the
	// throughput-optimal 128 because that is where the recall cost stops
	// reproducing across checkpoints; a config drift back to 128 is invisible in
	// every system metric and visible here.
	IndexEfSearch int32 `protobuf:"varint,6,opt,name=index_ef_search,json=indexEfSearch,proto3" json:"index_ef_search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_recsys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recsys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_recsys_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetIndexVersion() string {
	if x != nil {
		return x.IndexVersion
	}
	return ""
}

func (x *HealthResponse) GetIndexKind() string {
	if x != nil {
		return x.IndexKind
	}
	return ""
}

func (x *HealthResponse) GetIndexEfSearch() int32 {
	if x != nil {
		return x.IndexEfSearch
	}
	return 0
}

var File_recsys_proto protoreflect.FileDescriptor

const file_recsys_proto_rawDesc = "" +
	"\n" +
	"\frecsys.proto\x12\trecsys.v1\"\x90\x02\n" +
	"\x10RecommendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\asurface\x18\x02 \x01(\tR\asurface\x12\x1f\n" +
	"\vnum_results\x18\x03 \x01(\x05R\n" +
	"numResults\x12(\n" +
	"\x10exclude_item_ids\x18\x04 \x03(\tR\x0eexcludeItemIds\x12B\n" +
	"\acontext\x18\x05 \x03(\v2(.recsys.v1.RecommendRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\n" +
	"ScoredItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12I\n" +
	"\fdebug_scores\x18\x03 \x03(\v2&.recsys.v1.ScoredItem.DebugScoresEntryR\vdebugScores\x12\x18\n" +
	"\asources\x18\x04 \x03(\tR\asources\x12\x1e\n" +
	"\n" +
	"propensity\x18\x05 \x01(\x02R\n" +
	"propensity\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x1a>\n" +
	"\x10DebugScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xd9\x04\n" +
	"\x11RecommendResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.recsys.v1.ScoredItemR\x05items\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12#\n" +
	"\rindex_version\x18\x03 \x01(\tR\findexVersion\x12-\n" +
	"\x12experiment_variant\x18\x04 \x01(\tR\x11experimentVariant\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x05R\tlatencyMs\x12Z\n" +
	"\x10stage_latency_ms\x18\b \x03(\v20.recsys.v1.RecommendResponse.StageLatencyMsEntryR\x0estageLatencyMs\x12#\n" +
	"\rused_fallback\x18\x06 \x01(\bR\fusedFallback\x12)\n" +
	"\x10degraded_sources\x18\a \x03(\tR\x0fdegradedSources\x12P\n" +
	"\fstage_counts\x18\t \x03(\v2-.recsys.v1.RecommendResponse.StageCountsEntryR\vstageCounts\x1aA\n" +
	"\x13StageLatencyMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a>\n" +
	"\x10StageCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\xcf\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12#\n" +
	"\rindex_version\x18\x04 \x01(\tR\findexVersion\x12\x1d\n" +
	"\n" +
	"index_kind\x18\x05 \x01(\tR\tindexKind\x12&\n" +
	"\x0findex_ef_search\x18\x06 \x01(\x05R\rindexEfSearch2\x9d\x01\n" +
	"\vRecommender\x12O\n" +
	"\x12GetRecommendations\x12\x1b.recsys.v1.RecommendRequest\x1a\x1c.recsys.v1.RecommendResponse\x12=\n" +
	"\x06Health\x12\x18.recsys.v1.HealthRequest\x1a\x19.recsys.v1.HealthResponseBJZHgithub.com/MattyChoi/Recommender-System-Design/serving/go/internal/pb;pbb\x06proto3"

var (
	file_recsys_proto_rawDescOnce sync.Once
	file_recsys_proto_rawDescData []byte
)

func file_recsys_proto_rawDescGZIP() []byte {
	file_recsys_proto_rawDescOnce.Do(func() {
		file_recsys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recsys_proto_rawDesc), len(file_recsys_proto_rawDesc)))
	})
	return file_recsys_proto_rawDescData
}

var file_recsys_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_recsys_proto_goTypes = []any{
	(*RecommendRequest)(nil),  // 0: recsys.v1.RecommendRequest
	(*ScoredItem)(nil),        // 1: recsys.v1.ScoredItem
	(*RecommendResponse)(nil), // 2: recsys.v1.RecommendResponse
	(*HealthRequest)(nil),     // 3: recsys.v1.HealthRequest
	(*HealthResponse)(nil),    // 4: recsys.v1.HealthResponse
	nil,                       // 5: recsys.v1.RecommendRequest.ContextEntry
	nil,                       // 6: recsys.v1.ScoredItem.DebugScoresEntry
	nil,                       // 7: recsys.v1.RecommendResponse.StageLatencyMsEntry
	nil,                       // 8: recsys.v1.RecommendResponse.StageCountsEntry
}
var file_recsys_proto_depIdxs = []int32{
	5, // 0: recsys.v1.RecommendRequest.context:type_name -> recsys.v1.RecommendRequest.ContextEntry
	6, // 1: recsys.v1.ScoredItem.debug_scores:type_name -> recsys.v1.ScoredItem.DebugScoresEntry
	1, // 2: recsys.v1.RecommendResponse.items:type_name -> recsys.v1.ScoredItem
	7, // 3: recsys.v1.RecommendResponse.stage_latency_ms:type_name -> recsys.v1.RecommendResponse.StageLatencyMsEntry
	8, // 4: recsys.v1.RecommendResponse.stage_counts:type_name -> recsys.v1.RecommendResponse.StageCountsEntry
	0, // 5: recsys.v1.Recommender.GetRecommendations:input_type -> recsys.v1.RecommendRequest
	3, // 6: recsys.v1.Recommender.Health:input_type -> recsys.v1.HealthRequest
	2, // 7: recsys.v1.Recommender.GetRecommendations:output_type -> recsys.v1.RecommendResponse
	4, // 8: recsys.v1.Recommender.Health:output_type -> recsys.v1.HealthResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_recsys_proto_init() }
func file_recsys_proto_init() {
	if File_recsys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recsys_proto_rawDesc), len(file_recsys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recsys_proto_goTypes,
		DependencyIndexes: file_recsys_proto_depIdxs,
		MessageInfos:      file_recsys_proto_msgTypes,
	}.Build()
	File_recsys_proto = out.File
	file_recsys_proto_goTypes = nil
	file_recsys_proto_depIdxs = nil
}
