// The retrieval sidecar's contract: a user in, ranked candidates out.
//
// Regenerate stubs after any edit:  make proto
//
// ADR 0013 records why this service exists. The short version: a FAISS index is
// a C++ artifact the Go orchestrator cannot read, and `encode_user` is a
// PyTorch forward pass it cannot run. Those are two halves of one operation --
// embed the user, then look up neighbours -- so they live together behind one
// call rather than becoming two hops.
//
// This is a SEPARATE file from recsys.proto on purpose. That one is the
// product API, spoken to whatever renders the rail; this one is internal
// plumbing between two processes of the same system. Merging them would put
// `efSearch` in the same file as the thing a client app calls.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: retrieval.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetrieveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The EXTERNAL user id, the same string Feast keys its entities on.
	//
	// Not the internal index, and the asymmetry with items is deliberate. The
	// item side needs an index because the embedding table is indexed by
	// position. **The user side has no such table**: `encode_user` is
	// `cat([user_norm(user_feats), normalise(pooled_history)])` and never
	// embeds a user id at all. So the only thing an index could do here is key
	// the embedding cache, and requiring one would drag a ~1M-entry user_map
	// into the serving path to do a job a string already does.
	//
	// It is therefore also the cache key, which matters beyond this service:
	// ADR 0013's rung 2 has the Go orchestrator read the same key when this
	// service is unreachable.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	K      int32  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	// The user's recent history as internal item indices, most recent first.
	//
	// Sent rather than fetched here, because the orchestrator has already paid
	// for it: §14.2 fetches user features and history before the fan-out, and a
	// sidecar that re-read them would double the feature-store load and could
	// read a DIFFERENT snapshot than the one the ranker's features came from.
	// Empty is legal and means a cold user.
	//
	// The mask `encode_user` also wants is derived here rather than sent: a
	// variable-length list already carries which entries are real, and sending a
	// parallel mask would create a way for the two to disagree.
	History []int32 `protobuf:"varint,3,rep,packed,name=history,proto3" json:"history,omitempty"`
	// The RAW static user block, in `serving/features/columns.py`'s
	// USER_COLUMNS order -- `user_impressions_24h`, `user_clicks_24h`,
	// `user_ctr_smoothed`, `user_tenure_hours` per docs/design.md §4b.
	//
	// ⚠️ **Raw, and NOT the tower's input.** The tower is fitted on nine
	// columns: these four with log1p on the three counts, plus
	// `has_user_features` and sin/cos pairs for hour-of-day and day-of-week. The
	// sidecar assembles those by calling the same
	// `models.retrieval.dataloader.dataset.build_user_features` that training
	// calls, so the transform has exactly one implementation.
	//
	// This field used to be described as "the column order the tower was trained
	// with", and the gateway sent these four in good faith. The result was
	// InvalidArgument on every retrieval call and a popularity slate on every
	// request, the first time the stack ran end to end.
	//
	// Sent rather than fetched for the same reason as history: the
	// orchestrator's §14.2 feature fetch has already paid for it, and a second
	// read could see a different snapshot than the ranker's own features came
	// from.
	//
	// **Width is checked against the loaded tower, not trusted.** A short or
	// permuted vector is a correctly-typed request that produces a plausible
	// embedding for a user who does not exist, and the neighbours it retrieves
	// look entirely reasonable.
	UserFeats []float32 `protobuf:"fixed32,5,rep,packed,name=user_feats,json=userFeats,proto3" json:"user_feats,omitempty"`
	// Whether the feature store actually had a row for this user.
	//
	// This is `GetUserResponse.found`, forwarded. It becomes the tower's
	// `has_user_features` column, so it is a MODEL INPUT rather than telemetry:
	// the gateway serves zeros on a miss, and this flag is the only thing
	// distinguishing "a user with genuinely zero impressions" from "a user the
	// store has never seen". Defaulting it to false on a hit would tell the
	// tower every user is cold.
	HasUserFeatures bool `protobuf:"varint,6,opt,name=has_user_features,json=hasUserFeatures,proto3" json:"has_user_features,omitempty"`
	// efSearch for this request, 0 for the server's configured default.
	//
	// Per-request because it is the one index knob worth sweeping against live
	// traffic: ADR 0002 picked 512 over the throughput-optimal 128 on a recall
	// cost that did not reproduce across checkpoints, and an experiment arm that
	// can move it is how that gets settled on this corpus rather than on that
	// one.
	EfSearch      int32 `protobuf:"varint,4,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_retrieval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{0}
}

func (x *RetrieveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RetrieveRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *RetrieveRequest) GetHistory() []int32 {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *RetrieveRequest) GetUserFeats() []float32 {
	if x != nil {
		return x.UserFeats
	}
	return nil
}

func (x *RetrieveRequest) GetHasUserFeatures() bool {
	if x != nil {
		return x.HasUserFeatures
	}
	return false
}

func (x *RetrieveRequest) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

type RetrieveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Item indices, best first. Never contains 0: that is the reserved
	// out-of-vocabulary row, which is not an article and must not occupy a slot.
	Items []int32 `protobuf:"varint,1,rep,packed,name=items,proto3" json:"items,omitempty"`
	// Inner-product scores, aligned with items. Cosine, because both towers
	// L2-normalise -- an un-normalised table would rank by magnitude and say
	// nothing about it.
	//
	// This is `retrieval_score`, the ranker's first column. Returned rather than
	// recomputed downstream: the orchestrator has no item embeddings, and a
	// second process computing the same dot product from a second copy of the
	// table is a skew surface for no gain.
	Scores []float32 `protobuf:"fixed32,2,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	// `content_similarity`, the ranker's seventh column: the dot product of the
	// user's L2-normalised pooled history content vector with each candidate's
	// content vector.
	//
	// Computed here for the same reason as scores, and cheaply: this process
	// already holds the content table and already has the history. It mirrors
	// models/ranking/dataset.py:build exactly -- pooled is normalised, the
	// candidate vector is NOT -- because the ranker was fitted on that
	// asymmetry and normalising both here would quietly change the feature.
	ContentSimilarity []float32 `protobuf:"fixed32,6,rep,packed,name=content_similarity,json=contentSimilarity,proto3" json:"content_similarity,omitempty"`
	// Whether the user embedding came from cache rather than a tower forward
	// pass. §14.4's Redis cache is a latency optimisation, and a cache that has
	// quietly stopped being hit is a latency regression with no error attached.
	EmbeddingCached bool `protobuf:"varint,3,opt,name=embedding_cached,json=embeddingCached,proto3" json:"embedding_cached,omitempty"`
	// Which index answered: "hnsw" or "flat". The sidecar degrades to exact
	// search if the HNSW artifact fails to load, which is CORRECT and much
	// slower, and is otherwise invisible.
	IndexKind     string `protobuf:"bytes,4,opt,name=index_kind,json=indexKind,proto3" json:"index_kind,omitempty"`
	IndexVersion  string `protobuf:"bytes,5,opt,name=index_version,json=indexVersion,proto3" json:"index_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_retrieval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveResponse) GetItems() []int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RetrieveResponse) GetScores() []float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *RetrieveResponse) GetContentSimilarity() []float32 {
	if x != nil {
		return x.ContentSimilarity
	}
	return nil
}

func (x *RetrieveResponse) GetEmbeddingCached() bool {
	if x != nil {
		return x.EmbeddingCached
	}
	return false
}

func (x *RetrieveResponse) GetIndexKind() string {
	if x != nil {
		return x.IndexKind
	}
	return ""
}

func (x *RetrieveResponse) GetIndexVersion() string {
	if x != nil {
		return x.IndexVersion
	}
	return ""
}

type RetrievalHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalHealthRequest) Reset() {
	*x = RetrievalHealthRequest{}
	mi := &file_retrieval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalHealthRequest) ProtoMessage() {}

func (x *RetrievalHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalHealthRequest.ProtoReflect.Descriptor instead.
func (*RetrievalHealthRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{2}
}

type RetrievalHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	IndexKind     string                 `protobuf:"bytes,3,opt,name=index_kind,json=indexKind,proto3" json:"index_kind,omitempty"`
	IndexVersion  string                 `protobuf:"bytes,4,opt,name=index_version,json=indexVersion,proto3" json:"index_version,omitempty"`
	IndexEfSearch int32                  `protobuf:"varint,5,opt,name=index_ef_search,json=indexEfSearch,proto3" json:"index_ef_search,omitempty"`
	// Items actually in the loaded index. A rebuild that silently shipped a
	// fraction of the catalogue passes every other check here.
	ItemCount     int32 `protobuf:"varint,6,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalHealthResponse) Reset() {
	*x = RetrievalHealthResponse{}
	mi := &file_retrieval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalHealthResponse) ProtoMessage() {}

func (x *RetrievalHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalHealthResponse.ProtoReflect.Descriptor instead.
func (*RetrievalHealthResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{3}
}

func (x *RetrievalHealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *RetrievalHealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *RetrievalHealthResponse) GetIndexKind() string {
	if x != nil {
		return x.IndexKind
	}
	return ""
}

func (x *RetrievalHealthResponse) GetIndexVersion() string {
	if x != nil {
		return x.IndexVersion
	}
	return ""
}

func (x *RetrievalHealthResponse) GetIndexEfSearch() int32 {
	if x != nil {
		return x.IndexEfSearch
	}
	return 0
}

func (x *RetrievalHealthResponse) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

var File_retrieval_proto protoreflect.FileDescriptor

const file_retrieval_proto_rawDesc = "" +
	"\n" +
	"\x0fretrieval.proto\x12\trecsys.v1\"\xba\x01\n" +
	"\x0fRetrieveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\x12\x18\n" +
	"\ahistory\x18\x03 \x03(\x05R\ahistory\x12\x1d\n" +
	"\n" +
	"user_feats\x18\x05 \x03(\x02R\tuserFeats\x12*\n" +
	"\x11has_user_features\x18\x06 \x01(\bR\x0fhasUserFeatures\x12\x1b\n" +
	"\tef_search\x18\x04 \x01(\x05R\befSearch\"\xde\x01\n" +
	"\x10RetrieveResponse\x12\x14\n" +
	"\x05items\x18\x01 \x03(\x05R\x05items\x12\x16\n" +
	"\x06scores\x18\x02 \x03(\x02R\x06scores\x12-\n" +
	"\x12content_similarity\x18\x06 \x03(\x02R\x11contentSimilarity\x12)\n" +
	"\x10embedding_cached\x18\x03 \x01(\bR\x0fembeddingCached\x12\x1d\n" +
	"\n" +
	"index_kind\x18\x04 \x01(\tR\tindexKind\x12#\n" +
	"\rindex_version\x18\x05 \x01(\tR\findexVersion\"\x18\n" +
	"\x16RetrievalHealthRequest\"\xd2\x01\n" +
	"\x17RetrievalHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"index_kind\x18\x03 \x01(\tR\tindexKind\x12#\n" +
	"\rindex_version\x18\x04 \x01(\tR\findexVersion\x12&\n" +
	"\x0findex_ef_search\x18\x05 \x01(\x05R\rindexEfSearch\x12\x1d\n" +
	"\n" +
	"item_count\x18\x06 \x01(\x05R\titemCount2\xa1\x01\n" +
	"\tRetrieval\x12C\n" +
	"\bRetrieve\x12\x1a.recsys.v1.RetrieveRequest\x1a\x1b.recsys.v1.RetrieveResponse\x12O\n" +
	"\x06Health\x12!.recsys.v1.RetrievalHealthRequest\x1a\".recsys.v1.RetrievalHealthResponseBJZHgithub.com/MattyChoi/Recommender-System-Design/serving/go/internal/pb;pbb\x06proto3"

var (
	file_retrieval_proto_rawDescOnce sync.Once
	file_retrieval_proto_rawDescData []byte
)

func file_retrieval_proto_rawDescGZIP() []byte {
	file_retrieval_proto_rawDescOnce.Do(func() {
		file_retrieval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_retrieval_proto_rawDesc), len(file_retrieval_proto_rawDesc)))
	})
	return file_retrieval_proto_rawDescData
}

var file_retrieval_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_retrieval_proto_goTypes = []any{
	(*RetrieveRequest)(nil),         // 0: recsys.v1.RetrieveRequest
	(*RetrieveResponse)(nil),        // 1: recsys.v1.RetrieveResponse
	(*RetrievalHealthRequest)(nil),  // 2: recsys.v1.RetrievalHealthRequest
	(*RetrievalHealthResponse)(nil), // 3: recsys.v1.RetrievalHealthResponse
}
var file_retrieval_proto_depIdxs = []int32{
	0, // 0: recsys.v1.Retrieval.Retrieve:input_type -> recsys.v1.RetrieveRequest
	2, // 1: recsys.v1.Retrieval.Health:input_type -> recsys.v1.RetrievalHealthRequest
	1, // 2: recsys.v1.Retrieval.Retrieve:output_type -> recsys.v1.RetrieveResponse
	3, // 3: recsys.v1.Retrieval.Health:output_type -> recsys.v1.RetrievalHealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_retrieval_proto_init() }
func file_retrieval_proto_init() {
	if File_retrieval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_retrieval_proto_rawDesc), len(file_retrieval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_retrieval_proto_goTypes,
		DependencyIndexes: file_retrieval_proto_depIdxs,
		MessageInfos:      file_retrieval_proto_msgTypes,
	}.Build()
	File_retrieval_proto = out.File
	file_retrieval_proto_goTypes = nil
	file_retrieval_proto_depIdxs = nil
}
