package features

import (
	"context"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/MattyChoi/Recommender-System-Design/serving/go/internal/service"
)

// The parity fixture, generated by scripts/dump_parity_fixtures.py from
// models.ranking.dataset.feature_columns. Regenerate deliberately; a fixture
// that moves silently is a parity test re-pointed at new behaviour rather than
// one that caught it.
const featureFixture = "../../../testdata/feature_cases.json"

type featureCase struct {
	Name  string   `json:"name"`
	Names []string `json:"names"`

	RetrievalScore    []float32 `json:"retrieval_score"`
	PriorClicks       []float32 `json:"prior_clicks"`
	TrainClicks       []float32 `json:"train_clicks"`
	ContentSimilarity []float32 `json:"content_similarity"`
	HistoryLength     []int32   `json:"history_length"`
	Category          []int32   `json:"category"`
	Subcategory       []int32   `json:"subcategory"`

	// An ordered array, not an object: the generator sorts keys, so anything
	// carried as an object loses its order on the way out. The blend fixture
	// documents the version of this mistake that actually happened.
	Ranks []struct {
		Name  string  `json:"name"`
		Ranks []int32 `json:"ranks"`
	} `json:"ranks"`

	Expected [][]float32 `json:"expected"`
}

func loadFeatureCases(t *testing.T) []featureCase {
	t.Helper()
	raw, err := os.ReadFile(filepath.Clean(featureFixture))
	if err != nil {
		t.Fatalf("reading fixture: %v (run `uv run python -m scripts.dump_parity_fixtures`)", err)
	}
	var cases []featureCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("fixture is empty; a parity test over no cases passes and proves nothing")
	}
	return cases
}

// fixtureItems replays the store columns the Python side was handed.
type fixtureItems struct {
	prior []float32
	train []float32
}

func (f fixtureItems) ItemRows(
	_ context.Context, items []int32,
) ([][]float32, []string, []bool, error) {
	rows := make([][]float32, len(items))
	for index := range items {
		rows[index] = []float32{f.prior[index], f.train[index]}
	}
	return rows, []string{StorePriorClicks, StoreTrainClicks}, make([]bool, len(items)), nil
}

// TestFeatureMatrixMatchesPython is the third parity surface, after the blend
// and the re-ranker.
//
// The offline matrix produced every ranking number this project has measured.
// If the serving matrix disagrees, the model scores a different world at
// request time than the one it was fitted and evaluated on -- and nothing
// reports it, because both matrices have the same shape, the same dtype and
// entirely plausible values.
func TestFeatureMatrixMatchesPython(t *testing.T) {
	for _, testCase := range loadFeatureCases(t) {
		t.Run(testCase.Name, func(t *testing.T) {
			width := len(testCase.RetrievalScore)

			// Synthetic item ids. The fixture's columns are already indexed per
			// candidate, so the ids only have to be distinct and positive --
			// what is under test is the assembly, not the lookup.
			items := make([]int32, width)
			model := service.Columns{
				Score:      map[int32]float32{},
				Similarity: map[int32]float32{},
			}
			for index := 0; index < width; index++ {
				items[index] = int32(index + 1)
				model.Score[items[index]] = testCase.RetrievalScore[index]
				model.Similarity[items[index]] = testCase.ContentSimilarity[index]
			}

			ranks := map[string][]int32{}
			for _, source := range testCase.Ranks {
				ranks[source.Name] = source.Ranks
			}

			// history_length is per candidate in the fixture and per REQUEST in
			// the orchestrator, which serves one request at a time. They agree
			// only if the column is constant across the case; asserted rather
			// than assumed, because a fixture that varied it would be testing
			// something this builder cannot express.
			for _, value := range testCase.HistoryLength {
				if value != testCase.HistoryLength[0] {
					t.Fatalf("history_length varies within one request: %v", testCase.HistoryLength)
				}
			}
			history := make([]int32, testCase.HistoryLength[0])
			for index := range history {
				history[index] = int32(index + 1)
			}

			builder := &Builder{
				Items: fixtureItems{prior: testCase.PriorClicks, train: testCase.TrainClicks},
				Catalogue: fakeCatalogue{
					categories:    testCase.Category,
					subcategories: testCase.Subcategory,
				},
				Names: testCase.Names,
			}

			got, err := builder.Build(context.Background(), service.BuildInput{
				User:  service.User{ID: "U1", History: history},
				Items: items,
				Ranks: ranks,
				Model: model,
			})
			if err != nil {
				t.Fatalf("Build: %v", err)
			}

			if len(got.Rows) != len(testCase.Expected) {
				t.Fatalf("%d rows, Python produced %d", len(got.Rows), len(testCase.Expected))
			}
			for row := range testCase.Expected {
				if len(got.Rows[row]) != len(testCase.Expected[row]) {
					t.Fatalf("row %d has %d columns, Python produced %d",
						row, len(got.Rows[row]), len(testCase.Expected[row]))
				}
				for slot, want := range testCase.Expected[row] {
					// Exact would be defensible -- both sides end in float32 --
					// but the fixture round-trips through JSON's decimal text,
					// so a tolerance below anything that could change a
					// decision is the honest comparison.
					if math.Abs(float64(got.Rows[row][slot]-want)) > 1e-6 {
						t.Errorf("row %d, column %q: got %v, Python produced %v",
							row, testCase.Names[slot], got.Rows[row][slot], want)
					}
				}
			}
		})
	}
}

// TestTheFixtureCoversTheColumnsThisBuilderClaims guards the failure mode a
// parity test cannot catch on its own: agreement on a subset.
//
// Every case could pass while a column neither side exercises drifts apart.
// The full-FEATURES cases must therefore cover every column the builder knows
// how to produce.
func TestTheFixtureCoversTheColumnsThisBuilderClaims(t *testing.T) {
	covered := map[string]bool{}
	for _, testCase := range loadFeatureCases(t) {
		for _, name := range testCase.Names {
			covered[name] = true
		}
	}

	for _, name := range featureOrder {
		if !covered[name] {
			t.Errorf("column %q is built here but appears in no fixture case", name)
		}
	}
}
