package retrieval

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The parity fixture, generated by scripts/dump_parity_fixtures.py from the
// Python implementation. Regenerate deliberately; a fixture that moves silently
// is a parity test re-pointed at new behaviour rather than one that caught it.
const fixturePath = "../../../testdata/blend_cases.json"

type blendCase struct {
	Name          string  `json:"name"`
	MaxCandidates int     `json:"max_candidates"`
	Quotas        []int   `json:"quotas"`
	ExpectedItems []int32 `json:"expected_items"`

	// Arrays, not objects. quotas[i] belongs to sources[i], and a JSON object
	// cannot carry that pairing -- the generator sorts keys, so an object would
	// serialise alphabetically while the quotas stayed in declaration order.
	// The first version of the fixture did exactly that and would have handed
	// the first quota to the wrong source here, producing a plausible wrong
	// slate and a failure that looked like a Go bug.
	Sources []struct {
		Name string  `json:"name"`
		Top  []int32 `json:"top"`
	} `json:"sources"`
	ExpectedRanks []struct {
		Name  string  `json:"name"`
		Ranks []int32 `json:"ranks"`
	} `json:"expected_ranks"`
}

func loadBlendCases(t *testing.T) []blendCase {
	t.Helper()
	raw, err := os.ReadFile(filepath.Clean(fixturePath))
	if err != nil {
		t.Fatalf("reading fixture: %v (run `uv run python -m scripts.dump_parity_fixtures`)", err)
	}
	var cases []blendCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("fixture is empty; a parity test over no cases passes and proves nothing")
	}
	return cases
}

// TestBlendMatchesPython is the whole point of this file. The offline blend
// produced every candidate set this project has measured; if the serving blend
// disagrees, every offline number describes a system that was never served.
func TestBlendMatchesPython(t *testing.T) {
	for _, testCase := range loadBlendCases(t) {
		t.Run(testCase.Name, func(t *testing.T) {
			sources := make([]Source, len(testCase.Sources))
			for index, source := range testCase.Sources {
				sources[index] = Source{Name: source.Name, Top: source.Top}
			}

			got, err := Blend(sources, testCase.MaxCandidates, testCase.Quotas)
			if err != nil {
				t.Fatalf("Blend: %v", err)
			}

			if !equalInt32(got.Items, testCase.ExpectedItems) {
				t.Errorf("items: got %v, Python gave %v", got.Items, testCase.ExpectedItems)
			}

			if len(got.Ranks) != len(testCase.ExpectedRanks) {
				t.Fatalf("ranks: got %d sources, Python gave %d",
					len(got.Ranks), len(testCase.ExpectedRanks))
			}
			for index, expected := range testCase.ExpectedRanks {
				actual := got.Ranks[index]
				if actual.Name != expected.Name {
					t.Errorf("ranks[%d]: got source %q, Python gave %q",
						index, actual.Name, expected.Name)
				}
				if !equalInt32(actual.Ranks, expected.Ranks) {
					t.Errorf("ranks[%s]: got %v, Python gave %v",
						expected.Name, actual.Ranks, expected.Ranks)
				}
			}
		})
	}
}

// TestBlendIsDeterministic is the control for the Go-specific hazard. Python
// dicts preserve insertion order; Go maps do not. A port that accumulated
// candidates into a map would pass the parity test on some runs and fail on
// others, so a single green run above is not evidence of determinism.
func TestBlendIsDeterministic(t *testing.T) {
	sources := []Source{
		{Name: "a", Top: []int32{5, 9, 2, 7, 4, 8, 1, 3, 6}},
		{Name: "b", Top: []int32{9, 1, 3, 5, 7, 2, 8, 4, 6}},
	}

	first, err := Blend(sources, 6, []int{3, 3})
	if err != nil {
		t.Fatalf("Blend: %v", err)
	}
	for attempt := 0; attempt < 50; attempt++ {
		again, err := Blend(sources, 6, []int{3, 3})
		if err != nil {
			t.Fatalf("Blend: %v", err)
		}
		if !equalInt32(first.Items, again.Items) {
			t.Fatalf("attempt %d reordered the slate: %v then %v",
				attempt, first.Items, again.Items)
		}
	}
}

func TestBlendRejectsMismatchedQuotas(t *testing.T) {
	sources := []Source{{Name: "a", Top: []int32{1}}, {Name: "b", Top: []int32{2}}}

	if _, err := Blend(sources, 2, []int{2}); err == nil {
		t.Fatal("expected an error for 1 quota over 2 sources")
	}
}

// TestBlendNeverServesTheReservedRow pins the guard separately from the
// fixtures. Short source lists pad with zero, and the reserved row in front of
// a user is a placeholder rendered as a recommendation.
func TestBlendNeverServesTheReservedRow(t *testing.T) {
	sources := []Source{{Name: "a", Top: []int32{0, 0, 0}}, {Name: "b", Top: []int32{0, 4}}}

	got, err := Blend(sources, 5, []int{3, 2})
	if err != nil {
		t.Fatalf("Blend: %v", err)
	}
	for _, item := range got.Items {
		if item <= 0 {
			t.Fatalf("served reserved or invalid id %d in %v", item, got.Items)
		}
	}
}

func equalInt32(left, right []int32) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}
